### ISSUE TITLE
bind命令无法在MiraiMC v1.7下执行

### ISSUE THREAD

**Issue by JiangQiYan713** [DreamVoid/Whitelist4QQ#19]
【插件版本】
MiraiMC v1.7
Whitelist4QQ v1.1

【重现步骤】
1.在聊天栏执行命令/miraimc bind add 
2.什么也没有显示

【MiraiMC/config.yml】
```
http-api:
  url: http://localhost:8080
  message-fetch:
    interval: 10
    count: 10
httpapi:
  url: http://localhost:8080
  message-fetch:
    interval: 10
    count: 10
general:
  legacy-event-support: false
  check-update: true
  add-properties:
    mirai:
      no-desktop: true
      slider:
        captcha:
          supported: true
  mirai-core-version: 2.11.1
  maven-repo-url: https://maven.aliyun.com/nexus/content/groups/public/
  enable-http-api: false
  
  allow-bStats: true
  
  disable-safe-warning-message: false
  
  mirai-working-dir: default

bot:
  use-minecraft-logger:
    bot-logs: true
    network-logs: true
  
  disable-network-logs: true
  
  disable-bot-logs: true
  
  use-bukkit-logger:
    
    bot-logs: true
    
    network-logs: true
  
  log-events: false
  
  contact-cache:
    
    enable-friend-list-cache: false
    
    enable-group-member-list-cache: false
    
    save-interval-millis: 60000

database:
  
  type: sqlite
  
  mysql:
    
    address: localhost
    
    username: miraimc
    
    password: miraimc
    
    database: miraimc
    
    pool:
      
      connectionTimeout: 30000
      
      idleTimeout: 0
      
      maxLifetime: 0
      
      maximumPoolSize: 15
      
      keepaliveTime: 0
      
      minimumIdle: 5


```

【Whitelist4QQ/config.yml】
```
#  _          __  _   _   _   _____   _____   _       _   _____   _____   _   _   _____     _____
# | |        / / | | | | | | |_   _| | ____| | |     | | /  ___/ |_   _| | | | | /  _  \   /  _  \
# | |  __   / /  | |_| | | |   | |   | |__   | |     | | | |___    | |   | |_| | | | | |   | | | |
# | | /  | / /   |  _  | | |   | |   |  __|  | |     | | \___  \   | |   \___  | | | | |   | | | |
# | |/   |/ /    | | | | | |   | |   | |___  | |___  | |  ___| |   | |       | | | |_| |_  | |_| |_
# |___/|___/     |_| |_| |_|   |_|   |_____| |_____| |_| /_____/   |_|       |_| \_______| \_______|
#  Whitelist4QQ 配置文件
#
# 作者：xingxing520, DreamVoid
# Github: https://github.com/DreamVoid/Whitelist4QQ

# 插件配置
general:
  # 允许 bStats 统计
  bStats: true

  # 白名单范围
  # join - 加入服务器 - 玩家加入服务器时检测是否在 MiraiMC 的绑定数据库，如果不在则踢出
  # action - 操作 - 玩家可以加入服务器，但如果不在 MiraiMC 的绑定数据库中则会阻止玩家进行任何操作
  # spec - 旁观者 - 玩家可以加入服务器，但游戏模式将设为旁观者模式。如果 action 同时启用，则不阻止玩家移动。获取白名单后游戏模式将设为 server.prop 设置的默认模式。
  # 注：join 只在玩家加入服务器时检测1次。action 和 spec 在玩家不在数据库中时每 10 秒检测 1 次，如果在数据库就只检测 1 次。
  check-range:
    join: true
    action: false
    spec: false

  # 阻止已经绑定过 QQ 的 ID 重复绑定
  prevent-id-rebind: true

  # 阻止已经绑定过 ID 的 QQ 重复绑定
  prevent-qq-rebind: true

  # 踢出信息。在踢出不在 MiraiMC 数据库的玩家时显示的踢出消息
  # 默认提示消息使用的是 YAML 换行符，如果想使用单行消息可以设为 kick-message: "消息内容"
  kick-message: |-
    &b你还没有白名单，请加&eQQ群 383829380 &b到群内机器人申请。
    &b输入格式（例如）：#白名单 JiangQiYan
    &bSorry, you don't have permission to whitelist.
    &bPlease add QQ group 383829380 to apply for permission in the group.
    &bInput format(example)：#白名单 JiangQiYan

  # 游戏内消息提示。仅当 check-range 中的 join 设为 false（即允许玩家进入服务器）时才会出现。
  # 默认每3秒提示一次
  notify-message: |-
    &b========================================
    &e你不在本服的白名单内，将无法进行绝大多数操作
    &e要获取本服的白名单，请加入我们的QQ群进行申请
    &eQQ群：383829380
    &e如果你已经获取白名单，请稍等片刻或重新进入服务器
    &b========================================

  # 验证成功提示
  bind-success-message: "&a恭喜%id%成功获取了白名单，现在可以正常游玩服务器了！"

# 机器人配置
bot:
  # 用于接收验证的 QQ，只有存在于以下列表的机器人 QQ 的消息才会被处理
  # 请至少填写一个
  used-bot-accounts:
    - 488345943

  # 用于接收验证的 QQ 群，只有存在于以下列表的 QQ 群的消息才会被处理
  # 请至少填写一个
  used-group-numbers:
    - 383829380

  # 检测玩家绑定的 QQ 是否在群内，如果不在视为没有白名单
  check-qq-in-group: true

  # 有 QQ 退群时自动移除相应的绑定
  # 建议设为 false，这样一来就算熊孩子搞完事退群也有 QQ 留着做记录
  remove-bind-when-qq-quit: false

  # 让 Whitelist4QQ 处理 QQ 群内的绑定命令消息
  # 如果启用，请勿安装 Link2QQ 插件，避免玩家通过 Link2QQ 插件更换绑定从而绕过服务器管理员的审查
  # 如果禁用，除非管理员手动为玩家添加绑定，否则玩家将无法自行绑定 QQ，也就无法获得白名单
  use-group-message-command: true

  # 添加绑定消息前缀
  # 玩家需要发送“消息前缀+自己的ID”才会添加绑定
  # 例如：下方设置为“申请白名单”，玩家的ID是“123456”，则玩家需要在群内发送消息“申请白名单123456”
  bind-command-prefix: "#白名单 "

  # 消息
  # 插件向群内发送的所有消息都在这里配置
  messages:
    # 绑定成功
    bind-success: "白名单获取成功."

    # 绑定失败
    # 无论绑定失败的原因是什么，都只会发这一条
    # 可用变量：%id% - QQ绑定的ID
    bind-failed: |-
      绑定失败，此ID可能已经绑定另一个QQ，或你的QQ已经绑定了一个ID，请联系管理员处理！
      此QQ绑定的ID（游戏名称）：%id% 

```

【后台日志】
```
[05:11:15 INFO]: JiangQiYan issued server command: /miraimc bind add Tervita 2327311419
[05:11:15 WARN]: [MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 210044
java.lang.IllegalArgumentException: Invalid UUID string: Tervita
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.commands.MiraiMcCommand$1.run(MiraiMcCommand.java:53) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```
